adding gdpr stuff to news demo analytics
watson-developer-cloud/discovery-nodejs pull request #95
Opened 2018-05-17 19:21 UTC by savitanagaraj

https://github.com/watson-developer-cloud/discovery-nodejs/issues/94

2018-05-17 20:43 UTC, germanattanasio requested changes

2018-05-17 20:43 UTC, germanattanasio commented on src/index.js
```js
if (process.env.REACT_APP_BLUEMIX_ANALYTICS) {
	function loadAnalytics() {
	  const idaScript = document.createElement('script');
	  idaScript.src = '//www.ibm.com/common/stats/ida_stats.js';
	  document.head.appendChild(idaScript);
	}
    window.addEventListener('load', loadAnalytics);
}
```

2018-05-17 20:43 UTC, germanattanasio commented on src/index.js
>    if (process.env.REACT_APP_SEGMENT_KEY) {
remove this

2018-05-18 14:09 UTC, savitanagaraj commented
https://github.ibm.com/Watson-Discovery/discovery-tooling/issues/3434

2018-05-18 14:32 UTC, germanattanasio approved these changes

2018-05-18 14:32 UTC, merged